// Code generated by protoc-gen-go.
// source: responses.proto
// DO NOT EDIT!

package redditproto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LinkChildren struct {
	Data             *Link  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LinkChildren) Reset()         { *m = LinkChildren{} }
func (m *LinkChildren) String() string { return proto.CompactTextString(m) }
func (*LinkChildren) ProtoMessage()    {}

func (m *LinkChildren) GetData() *Link {
	if m != nil {
		return m.Data
	}
	return nil
}

type LinkData struct {
	Children         []*LinkChildren `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *LinkData) Reset()         { *m = LinkData{} }
func (m *LinkData) String() string { return proto.CompactTextString(m) }
func (*LinkData) ProtoMessage()    {}

func (m *LinkData) GetChildren() []*LinkChildren {
	if m != nil {
		return m.Children
	}
	return nil
}

type LinkListing struct {
	Data             *LinkData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *LinkListing) Reset()         { *m = LinkListing{} }
func (m *LinkListing) String() string { return proto.CompactTextString(m) }
func (*LinkListing) ProtoMessage()    {}

func (m *LinkListing) GetData() *LinkData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommentChildren struct {
	Data             *Comment `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CommentChildren) Reset()         { *m = CommentChildren{} }
func (m *CommentChildren) String() string { return proto.CompactTextString(m) }
func (*CommentChildren) ProtoMessage()    {}

func (m *CommentChildren) GetData() *Comment {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommentData struct {
	Children         []*CommentChildren `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CommentData) Reset()         { *m = CommentData{} }
func (m *CommentData) String() string { return proto.CompactTextString(m) }
func (*CommentData) ProtoMessage()    {}

func (m *CommentData) GetChildren() []*CommentChildren {
	if m != nil {
		return m.Children
	}
	return nil
}

type CommentListing struct {
	Data             *CommentData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CommentListing) Reset()         { *m = CommentListing{} }
func (m *CommentListing) String() string { return proto.CompactTextString(m) }
func (*CommentListing) ProtoMessage()    {}

func (m *CommentListing) GetData() *CommentData {
	if m != nil {
		return m.Data
	}
	return nil
}
